"""Export canonical Pydantic and FastAPI contracts as deterministic JSON files."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from app.main import app
from app.schemas.session_commands import command_schema
from app.schemas.session_events import event_schema


REPOSITORY_ROOT = Path(__file__).resolve().parents[2]
CONTRACTS_DIRECTORY = REPOSITORY_ROOT / "contracts"
GENERATED_BY = "Generated by backend/scripts/export_contracts.py; do not edit manually."


def write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(payload, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def exported_schema(schema: dict[str, Any]) -> dict[str, Any]:
    """Add JSON Schema metadata without modifying Pydantic's contract content."""
    return {
        "$comment": GENERATED_BY,
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        **schema,
    }


def main() -> None:
    write_json(CONTRACTS_DIRECTORY / "session-events.schema.json", exported_schema(event_schema()))
    write_json(CONTRACTS_DIRECTORY / "session-commands.schema.json", exported_schema(command_schema()))

    openapi = app.openapi()
    openapi["x-generated-by"] = GENERATED_BY
    write_json(CONTRACTS_DIRECTORY / "openapi.json", openapi)


if __name__ == "__main__":
    main()
